"""create fundamentals_snapshot table

Revision ID: 4248cfa08dd2
Revises: 856b7b973cc9
Create Date: 2026-06-02 20:34:11.985416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4248cfa08dd2'
down_revision: Union[str, Sequence[str], None] = '856b7b973cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamentals_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('per', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('forward_per', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pbr', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', name='uq_fundamentals_snapshot_instrument')
    )
    op.create_index('ix_fundamentals_snapshot_fetched_at', 'fundamentals_snapshot', ['fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fundamentals_snapshot_fetched_at', table_name='fundamentals_snapshot')
    op.drop_table('fundamentals_snapshot')
    # ### end Alembic commands ###
