"""create market_investor_flows table

Revision ID: 433bc73a2b38
Revises: 5b238138ed0d
Create Date: 2026-06-04 00:20:22.362786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433bc73a2b38'
down_revision: Union[str, Sequence[str], None] = '5b238138ed0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_investor_flows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('investor_type', sa.String(length=32), nullable=False),
    sa.Column('net_value', sa.BigInteger(), nullable=False),
    sa.Column('buy_value', sa.BigInteger(), nullable=True),
    sa.Column('sell_value', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'market', 'investor_type', name='uq_market_investor_flows_date_market_investor')
    )
    op.create_index('ix_market_investor_flows_investor_date', 'market_investor_flows', ['investor_type', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_investor_flows_investor_date', table_name='market_investor_flows')
    op.drop_table('market_investor_flows')
    # ### end Alembic commands ###
