"""create investor_flows table

Revision ID: 5b238138ed0d
Revises: 4039c0d363ce
Create Date: 2026-06-03 20:00:05.277070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b238138ed0d'
down_revision: Union[str, Sequence[str], None] = '4039c0d363ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_flows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('foreign_net_volume', sa.BigInteger(), nullable=False),
    sa.Column('foreign_hold_ratio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('institutional_net_volume', sa.BigInteger(), nullable=False),
    sa.Column('individual_net_volume', sa.BigInteger(), nullable=False),
    sa.Column('close_price', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'trade_date', name='uq_investor_flows_instrument_date')
    )
    op.create_index('ix_investor_flows_instrument_date', 'investor_flows', ['instrument_id', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_investor_flows_instrument_date', table_name='investor_flows')
    op.drop_table('investor_flows')
    # ### end Alembic commands ###
