"""add market column to instruments

Revision ID: cc53dfe03fb8
Revises: d26e4be4b983
Create Date: 2026-05-25 09:45:06.127525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc53dfe03fb8'
down_revision: Union[str, Sequence[str], None] = 'd26e4be4b983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('market', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'market')
    # ### end Alembic commands ###
